channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4
  - numpy=1.19
  - opencv=4.5
  - pandas=1.3  
  - pillow=8.0
  - h5py=3.6.0
  - pip:
    - tensorflow~=2.7.0
    - tensorflow-hub~=0.12.0
    
